### ISSUE TITLE
Please update idaplugin.py

### ISSUE THREAD

**Issue by HongThatCong** [mandiant/flare-floss#562]
Please update file idaplugin.py in scripts folder.
1. Add tigh strings scanning
2. Add the open json result file from floss.exe, add comments
3. Test with sample: B09D51E272E25E3EDC9FE7F76F5FE024
Error:
"
Z:\IDA\usrdir\idc\idaplugin.py: 'int' object is not subscriptable
Traceback (most recent call last):
  File "Z:\IDA\77\python\3\ida_idaapi.py", line 580, in IDAPython_ExecScript
    exec(code, g)
  File "Z:/IDA/usrdir/idc/idaplugin.py", line 184, in <module>
    main()
  File "Z:/IDA/usrdir/idc/idaplugin.py", line 162, in main
    vw, floss.identify.get_function_fvas(decoding_functions_candidates), MIN_LENGTH, disable_progress=True
  File "Z:\Python38\lib\site-packages\floss\identify.py", line 89, in get_function_fvas
    return list(map(lambda p: p[0], functions))
  File "Z:\Python38\lib\site-packages\floss\identify.py", line 89, in <lambda>
    return list(map(lambda p: p[0], functions))
TypeError: 'int' object is not subscriptable
"
Thanks for excellent tool.

**Comment by HongThatCong** [comment]
Yes, @mr-tz. It work. 
I like to run floss directly in IDA

**Comment by mr-tz** [comment]
Hello, @HongThatCong, can you check out if the updates in #580 match your needs?
