### ISSUE TITLE
python 3.12 installation 

### ISSUE THREAD

**Issue by GeneriicName** [mandiant/flare-floss#980]
when trying to pip install the package in python 3.12 (windows 11) i get the following error
```
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 2769: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```
i prefer not to downgrade, hoping anyone has a soltuion
thanks in advance!

**Comment by williballenthin** [comment]
would you share a bit more of the stack trace please? I'm not sure which line this comes from.

**Comment by GeneriicName** [comment]
> would you share a bit more of the stack trace please? I'm not sure which line this comes from.


thanks for the response!
this is the full traceback 
```
PS C:\Users\user> py -m pip install flare-floss
Collecting flare-floss
  Using cached flare_floss-3.0.1-py3-none-any.whl.metadata (5.5 kB)
Collecting tabulate==0.9.0 (from flare-floss)
  Using cached tabulate-0.9.0-py3-none-any.whl.metadata (34 kB)
Collecting vivisect==1.1.1 (from flare-floss)
  Using cached vivisect-1.1.1-py3-none-any.whl.metadata (2.8 kB)
Collecting viv-utils==0.7.9 (from viv-utils[flirt]==0.7.9->flare-floss)
  Using cached viv_utils-0.7.9-py2.py3-none-any.whl.metadata (1.2 kB)
Collecting pydantic==1.10.9 (from flare-floss)
  Using cached pydantic-1.10.9-py3-none-any.whl.metadata (147 kB)
Collecting tqdm==4.65.0 (from flare-floss)
  Using cached tqdm-4.65.0-py3-none-any.whl.metadata (56 kB)
Collecting networkx==3.1 (from flare-floss)
  Using cached networkx-3.1-py3-none-any.whl.metadata (5.3 kB)
Collecting halo==0.0.31 (from flare-floss)
  Using cached halo-0.0.31.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting rich==13.4.2 (from flare-floss)
  Using cached rich-13.4.2-py3-none-any.whl.metadata (18 kB)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\user\appdata\local\programs\python\python312\lib\site-packages (from flare-floss) (2023.2.7)
Collecting binary2strings==0.1.13 (from flare-floss)
  Using cached binary2strings-0.1.13.tar.gz (59 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-_0up553l\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 30, in <module>
        File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1255.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x8c in position 2769: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by williballenthin** [comment]
interesting this is an install-time crash, not runtime. 

looks like `binary2strings` is failing to install, and along the way, there's a bug in the setup utility when it writes to the console. 

@GeneriicName do you see the same thing if you try to install `binary2strings` via pip directly?

**Comment by williballenthin** [comment]
@GeneriicName what terminal are you using? Windows Terminal? or ps1? or cmd.exe?

**Comment by GeneriicName** [comment]
@williballenthin yes, exact same error when installng `binary2strings`, would you suggest opening an issue there? 
and i used both cmd, PowerShell and the terminal of pycharm, and on two diffrent computers

**Comment by williballenthin** [comment]
Yeah unfortunately I think you should report it there. If they aren't responsive to fixing the issue, then we can look into replacing the dependency so that floss works on 3.12.

**Comment by GeneriicName** [comment]
i opend a new issue [https://github.com/glmcdona/binary2strings/issues/22](url)
hopefully they can resolve it
thanks for your help!

**Comment by GeneriicName** [comment]
will reopen if needed
